### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by suustenvoorde** [SjorsWijsman/web-app-from-scratch-2021#3]
Mooie app, ziet er erg goed uit! Een paar tips:

- Wat is precies je concept? Hoe kun je straks nummers gaan ranken? Ik ben benieuwd, werk dat voor jezelf nog even uit (door bijvoorbeeld een schets te maken) en neem dit mee in je READme
- Nice van de bronvermelding in de code comments
- [Jonah](https://github.com/theonejonahgold/web-app-from-scratch-2021) heeft ervoor gezorgd dat de API token niet meer in de URL komt te staan, leuk om eens te checken (nice to have)
- Complimenten hoe overzichtelijk en DRY de code is!

**Comment by SjorsWijsman** [comment]
Bedankt voor de feedback! Ondertussen heb ik ook ervoor gezorgd dat de API token niet meer in de URL staat.
