### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by NielsPeeters96** [SjorsWijsman/web-app-from-scratch-2021#4]
Als ik naar je code kijk denk ik bij mezelf zit Sjors nog op deze minor of is die daar al klaar mee? Ziet er echt top uit en ik kan er zelf heel veel van leren. Moet binnen mijn eigen project nog modules toepassen en dat kan ik zeker doen met die van jouw als voorbeeld!

**Comment by SjorsWijsman** [comment]
Haha thanks, laat maar weten als ik nog iets voor je kan uitleggen van m'n code!
